name: Robot Framework Tests

on: push

jobs:
  api_tests:
    name: API Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run API Tests
        run: robot --name "Test Results" --outputdir logs/api tests/api/

      - name: Upload API Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-results
          path: logs/

  e2e_tests:
    name: E2E Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run E2E Tests
        run: robot --name "Test Results" -v OPTIONS:"add_argument('--headless')" --outputdir logs/ tests/e2e

      - name: Upload E2E Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: logs/
          
  deploy:
    name: Deploy Test Results 📊
    runs-on: ubuntu-latest
    needs: 
      - api_tests
      - e2e_tests
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://lucas-scandido.github.io/challenge-robot-ambev/log.html

    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install Dependencies
      run: pip install robotframework 

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with: 
        path: logs/

    - name: Merge Report
      run: rebot --merge logs/api-test-results/output.xml logs/e2e-test-results/output.xml

    - name: Upload Merge Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ./*.html
      
    - name: Setup Pages
      uses: actions/configure-pages@v5
 
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with: 
        name: test-results

    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./

    - name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@v4       